name: SW_svile
authors: ["svile", "TheNewManu"]
description: SkyWars plugin
main: svile\sw\SWmain
version: 0.7dev
api: [3.0.0-ALPHA8, 3.0,0-ALPHA9]
load: STARTUP

commands:
 sw:
  description: SkyWars main command
